### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by komomon** [resurrecting-open-source-projects/nbtscan#2] opened 2021-01-12 15:38 UTC
![image](https://user-images.githubusercontent.com/52700174/104336356-4850a280-552f-11eb-82cc-bdd2c726567b.png)

**Comment by eribertomota** [comment] 2021-01-12 21:24
Hi @komomon,

It is not a bug. You need install autoreconf as shown in error message.

In Kali you can use `# apt install nbtscan` to install directly from repositories.

I will close this bug.

Regards,

Eriberto

**Closed as completed by eribertomota** 2021-01-12 21:24 UTC
